version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nmudb
      POSTGRES_USER: nmu
      POSTGRES_PASSWORD: nmu_pass
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://nmu:nmu_pass@db:5432/nmudb
      JWT_SECRET: devsecret123
      ADMIN_EMAIL: xabiso@nmumail.nmu
      ADMIN_NAME: "Xabiso Mpofu"
      ADMIN_PASSWORD: ChangeThisAdminPass123!
      STORAGE_DIR: /app/uploads
      NODE_ENV: development
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run start"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - backend

volumes:
  db-data:
